import type { Metadata } from 'next'
import { Inter, Nunito } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar/Navbar';
import Modal from './components/modals/Modal';

const inter = Inter({ subsets: ['latin'] });
const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Navbar />
        <Modal actionLabel='Kiss me' isOpen title='hello world' />
        {children}
      </body>
    </html>
  )
}
